name: Update transcripts data

on:
  workflow_dispatch:
  schedule:
    # Every sunday at 12:33, 12:47, and 1:03 PM (respectively).
    - cron: '33 17 * * 0'
    - cron: '47 17 * * 0'
    - cron: '3 18 * * 0'
    - cron: '5 9 * * 0'
    - cron: '14 17 * * 0'
    # Every day at 2:03 AM EST (converted to UTC).
    - cron: '3 7 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install necessary tools
        run: |
          sudo apt update && sudo apt install build-essential ffmpeg cmake
          pip install yt-dlp requests
          curl -fsSL https://deno.land/install.sh | sh -s -- -y

      - name: Clone whisper.cpp
        run: git clone https://github.com/ggerganov/whisper.cpp

      - name: Build whisper.cpp
        run: |
          cd whisper.cpp
          make

      - name: Download tiny Whisper model
        run: ./whisper.cpp/models/download-ggml-model.sh tiny.en

      - name: Move tools to the working directory
        run: |
          mv whisper.cpp/build/bin/whisper-cli whisper-cli
          mv whisper.cpp/models/ggml-tiny.en.bin ggml-tiny.en.bin

      - name: Save cached cookies to a file
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: echo "$COOKIES" | base64 -d > cookies.txt

      - name: Run python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python3 ./data/update_data.py

      - name: Push files to GitHub
        if: ${{ success() || failure() || cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "fbcss"
          git config --global user.email "fbcss@fbcss.github.io"
          git add data/transcripts.json
          git commit -m "Automated transcription"
          git pull --rebase origin main
          git push -u origin main
