name: Update transcripts data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install necessary tools
        run: |
          sudo apt update && sudo apt install build-essential ffmpeg cmake
          pip install yt-dlp requests
          curl -fsSL https://deno.land/install.sh | sh -s -- -y

      - name: Clone whisper.cpp
        run: git clone https://github.com/ggerganov/whisper.cpp

      - name: Build whisper.cpp
        run: |
          cd whisper.cpp
          make

      - name: Download tiny Whisper model
        run: ./whisper.cpp/models/download-ggml-model.sh tiny.en

      - name: Move tools to the working directory
        run: |
          mv whisper.cpp/build/bin/whisper-cli whisper-cli
          mv whisper.cpp/models/ggml-tiny.en.bin ggml-tiny.en.bin

      - name: Save cached cookies to a file
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: echo "$COOKIES" | base64 -d > cookies.txt

      - name: Run python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python3 ./data/update_data.py

      - name: Push files to GitHub
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/transcripts.json
          git commit -m "Automated push from GitHub Actions workflow"
          git push -u origin main
